/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export interface LidoAdapterInterface extends utils.Interface {
  functions: {
    "PRECISION()": FunctionFragment;
    "accDeposit()": FunctionFragment;
    "accWithdraw()": FunctionFragment;
    "adaptorName()": FunctionFragment;
    "canDeposit(uint256)": FunctionFragment;
    "deposit()": FunctionFragment;
    "getAPR()": FunctionFragment;
    "getDepositAmount(uint256)": FunctionFragment;
    "getTokens()": FunctionFragment;
    "stETH()": FunctionFragment;
    "supportWithdraw()": FunctionFragment;
    "withdraw(uint256)": FunctionFragment;
    "wstETH()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "PRECISION"
      | "accDeposit"
      | "accWithdraw"
      | "adaptorName"
      | "canDeposit"
      | "deposit"
      | "getAPR"
      | "getDepositAmount"
      | "getTokens"
      | "stETH"
      | "supportWithdraw"
      | "withdraw"
      | "wstETH"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "PRECISION", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "accDeposit",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "accWithdraw",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "adaptorName",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "canDeposit",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(functionFragment: "deposit", values?: undefined): string;
  encodeFunctionData(functionFragment: "getAPR", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getDepositAmount",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(functionFragment: "getTokens", values?: undefined): string;
  encodeFunctionData(functionFragment: "stETH", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "supportWithdraw",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(functionFragment: "wstETH", values?: undefined): string;

  decodeFunctionResult(functionFragment: "PRECISION", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "accDeposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "accWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "adaptorName",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "canDeposit", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getAPR", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getDepositAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getTokens", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "stETH", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "supportWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "wstETH", data: BytesLike): Result;

  events: {};
}

export interface LidoAdapter extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: LidoAdapterInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    PRECISION(overrides?: CallOverrides): Promise<[BigNumber]>;

    accDeposit(overrides?: CallOverrides): Promise<[BigNumber]>;

    accWithdraw(overrides?: CallOverrides): Promise<[BigNumber]>;

    adaptorName(overrides?: CallOverrides): Promise<[string]>;

    canDeposit(
      amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    deposit(
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    getAPR(overrides?: CallOverrides): Promise<[BigNumber]>;

    getDepositAmount(
      amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getTokens(
      overrides?: CallOverrides
    ): Promise<
      [string, string, string] & {
        token0: string;
        token1: string;
        token2: string;
      }
    >;

    stETH(overrides?: CallOverrides): Promise<[string]>;

    supportWithdraw(overrides?: CallOverrides): Promise<[boolean]>;

    withdraw(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    wstETH(overrides?: CallOverrides): Promise<[string]>;
  };

  PRECISION(overrides?: CallOverrides): Promise<BigNumber>;

  accDeposit(overrides?: CallOverrides): Promise<BigNumber>;

  accWithdraw(overrides?: CallOverrides): Promise<BigNumber>;

  adaptorName(overrides?: CallOverrides): Promise<string>;

  canDeposit(
    amount: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  deposit(
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  getAPR(overrides?: CallOverrides): Promise<BigNumber>;

  getDepositAmount(
    amount: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getTokens(
    overrides?: CallOverrides
  ): Promise<
    [string, string, string] & {
      token0: string;
      token1: string;
      token2: string;
    }
  >;

  stETH(overrides?: CallOverrides): Promise<string>;

  supportWithdraw(overrides?: CallOverrides): Promise<boolean>;

  withdraw(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  wstETH(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    PRECISION(overrides?: CallOverrides): Promise<BigNumber>;

    accDeposit(overrides?: CallOverrides): Promise<BigNumber>;

    accWithdraw(overrides?: CallOverrides): Promise<BigNumber>;

    adaptorName(overrides?: CallOverrides): Promise<string>;

    canDeposit(
      amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    deposit(overrides?: CallOverrides): Promise<BigNumber>;

    getAPR(overrides?: CallOverrides): Promise<BigNumber>;

    getDepositAmount(
      amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getTokens(
      overrides?: CallOverrides
    ): Promise<
      [string, string, string] & {
        token0: string;
        token1: string;
        token2: string;
      }
    >;

    stETH(overrides?: CallOverrides): Promise<string>;

    supportWithdraw(overrides?: CallOverrides): Promise<boolean>;

    withdraw(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    wstETH(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    PRECISION(overrides?: CallOverrides): Promise<BigNumber>;

    accDeposit(overrides?: CallOverrides): Promise<BigNumber>;

    accWithdraw(overrides?: CallOverrides): Promise<BigNumber>;

    adaptorName(overrides?: CallOverrides): Promise<BigNumber>;

    canDeposit(
      amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    deposit(
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    getAPR(overrides?: CallOverrides): Promise<BigNumber>;

    getDepositAmount(
      amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getTokens(overrides?: CallOverrides): Promise<BigNumber>;

    stETH(overrides?: CallOverrides): Promise<BigNumber>;

    supportWithdraw(overrides?: CallOverrides): Promise<BigNumber>;

    withdraw(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    wstETH(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    PRECISION(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    accDeposit(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    accWithdraw(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    adaptorName(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    canDeposit(
      amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    deposit(
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    getAPR(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getDepositAmount(
      amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getTokens(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    stETH(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    supportWithdraw(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    withdraw(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    wstETH(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
