/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../common";

export declare namespace OperatorRegistry {
  export type ValidatorStruct = {
    pubKey: PromiseOrValue<BytesLike>;
    signature: PromiseOrValue<BytesLike>;
    depositDataRoot: PromiseOrValue<BytesLike>;
  };

  export type ValidatorStructOutput = [string, string, string] & {
    pubKey: string;
    signature: string;
    depositDataRoot: string;
  };
}

export interface FrxETHMinterInterface extends utils.Interface {
  functions: {
    "DEPOSIT_SIZE()": FunctionFragment;
    "RATIO_PRECISION()": FunctionFragment;
    "acceptOwnership()": FunctionFragment;
    "activeValidators(bytes)": FunctionFragment;
    "addValidator((bytes,bytes,bytes32))": FunctionFragment;
    "addValidators((bytes,bytes,bytes32)[])": FunctionFragment;
    "clearValidatorArray()": FunctionFragment;
    "currentWithheldETH()": FunctionFragment;
    "depositContract()": FunctionFragment;
    "depositEther(uint256)": FunctionFragment;
    "depositEtherPaused()": FunctionFragment;
    "frxETHToken()": FunctionFragment;
    "getValidator(uint256)": FunctionFragment;
    "getValidatorStruct(bytes,bytes,bytes32)": FunctionFragment;
    "moveWithheldETH(address,uint256)": FunctionFragment;
    "nominateNewOwner(address)": FunctionFragment;
    "nominatedOwner()": FunctionFragment;
    "numValidators()": FunctionFragment;
    "owner()": FunctionFragment;
    "popValidators(uint256)": FunctionFragment;
    "recoverERC20(address,uint256)": FunctionFragment;
    "recoverEther(uint256)": FunctionFragment;
    "removeValidator(uint256,bool)": FunctionFragment;
    "setTimelock(address)": FunctionFragment;
    "setWithdrawalCredential(bytes)": FunctionFragment;
    "setWithholdRatio(uint256)": FunctionFragment;
    "sfrxETHToken()": FunctionFragment;
    "submit()": FunctionFragment;
    "submitAndDeposit(address)": FunctionFragment;
    "submitAndGive(address)": FunctionFragment;
    "submitPaused()": FunctionFragment;
    "swapValidator(uint256,uint256)": FunctionFragment;
    "timelock_address()": FunctionFragment;
    "togglePauseDepositEther()": FunctionFragment;
    "togglePauseSubmits()": FunctionFragment;
    "withholdRatio()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "DEPOSIT_SIZE"
      | "RATIO_PRECISION"
      | "acceptOwnership"
      | "activeValidators"
      | "addValidator"
      | "addValidators"
      | "clearValidatorArray"
      | "currentWithheldETH"
      | "depositContract"
      | "depositEther"
      | "depositEtherPaused"
      | "frxETHToken"
      | "getValidator"
      | "getValidatorStruct"
      | "moveWithheldETH"
      | "nominateNewOwner"
      | "nominatedOwner"
      | "numValidators"
      | "owner"
      | "popValidators"
      | "recoverERC20"
      | "recoverEther"
      | "removeValidator"
      | "setTimelock"
      | "setWithdrawalCredential"
      | "setWithholdRatio"
      | "sfrxETHToken"
      | "submit"
      | "submitAndDeposit"
      | "submitAndGive"
      | "submitPaused"
      | "swapValidator"
      | "timelock_address"
      | "togglePauseDepositEther"
      | "togglePauseSubmits"
      | "withholdRatio"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "DEPOSIT_SIZE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "RATIO_PRECISION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "acceptOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "activeValidators",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "addValidator",
    values: [OperatorRegistry.ValidatorStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "addValidators",
    values: [OperatorRegistry.ValidatorStruct[]]
  ): string;
  encodeFunctionData(
    functionFragment: "clearValidatorArray",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "currentWithheldETH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "depositContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "depositEther",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "depositEtherPaused",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "frxETHToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getValidator",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getValidatorStruct",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "moveWithheldETH",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "nominateNewOwner",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "nominatedOwner",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "numValidators",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "popValidators",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "recoverERC20",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "recoverEther",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "removeValidator",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<boolean>]
  ): string;
  encodeFunctionData(
    functionFragment: "setTimelock",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "setWithdrawalCredential",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "setWithholdRatio",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "sfrxETHToken",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "submit", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "submitAndDeposit",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "submitAndGive",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "submitPaused",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "swapValidator",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "timelock_address",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "togglePauseDepositEther",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "togglePauseSubmits",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "withholdRatio",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "DEPOSIT_SIZE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "RATIO_PRECISION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "acceptOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "activeValidators",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addValidator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addValidators",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "clearValidatorArray",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "currentWithheldETH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositEther",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositEtherPaused",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "frxETHToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getValidator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getValidatorStruct",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "moveWithheldETH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nominateNewOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nominatedOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "numValidators",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "popValidators",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recoverERC20",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recoverEther",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeValidator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTimelock",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setWithdrawalCredential",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setWithholdRatio",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sfrxETHToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "submit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "submitAndDeposit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitAndGive",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitPaused",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapValidator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "timelock_address",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "togglePauseDepositEther",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "togglePauseSubmits",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withholdRatio",
    data: BytesLike
  ): Result;

  events: {
    "DepositEtherPaused(bool)": EventFragment;
    "DepositSent(bytes,bytes)": EventFragment;
    "ETHSubmitted(address,address,uint256,uint256)": EventFragment;
    "EmergencyERC20Recovered(address,uint256)": EventFragment;
    "EmergencyEtherRecovered(uint256)": EventFragment;
    "KeysCleared()": EventFragment;
    "OwnerChanged(address,address)": EventFragment;
    "OwnerNominated(address)": EventFragment;
    "SubmitPaused(bool)": EventFragment;
    "TimelockChanged(address)": EventFragment;
    "ValidatorAdded(bytes,bytes)": EventFragment;
    "ValidatorArrayCleared()": EventFragment;
    "ValidatorRemoved(bytes,uint256,bool)": EventFragment;
    "ValidatorsPopped(uint256)": EventFragment;
    "ValidatorsSwapped(bytes,bytes,uint256,uint256)": EventFragment;
    "WithdrawalCredentialSet(bytes)": EventFragment;
    "WithheldETHMoved(address,uint256)": EventFragment;
    "WithholdRatioSet(uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "DepositEtherPaused"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "DepositSent"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ETHSubmitted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "EmergencyERC20Recovered"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "EmergencyEtherRecovered"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "KeysCleared"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnerChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnerNominated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SubmitPaused"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TimelockChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ValidatorAdded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ValidatorArrayCleared"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ValidatorRemoved"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ValidatorsPopped"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ValidatorsSwapped"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "WithdrawalCredentialSet"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "WithheldETHMoved"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "WithholdRatioSet"): EventFragment;
}

export interface DepositEtherPausedEventObject {
  new_status: boolean;
}
export type DepositEtherPausedEvent = TypedEvent<
  [boolean],
  DepositEtherPausedEventObject
>;

export type DepositEtherPausedEventFilter =
  TypedEventFilter<DepositEtherPausedEvent>;

export interface DepositSentEventObject {
  pubKey: string;
  withdrawalCredential: string;
}
export type DepositSentEvent = TypedEvent<
  [string, string],
  DepositSentEventObject
>;

export type DepositSentEventFilter = TypedEventFilter<DepositSentEvent>;

export interface ETHSubmittedEventObject {
  sender: string;
  recipient: string;
  sent_amount: BigNumber;
  withheld_amt: BigNumber;
}
export type ETHSubmittedEvent = TypedEvent<
  [string, string, BigNumber, BigNumber],
  ETHSubmittedEventObject
>;

export type ETHSubmittedEventFilter = TypedEventFilter<ETHSubmittedEvent>;

export interface EmergencyERC20RecoveredEventObject {
  tokenAddress: string;
  tokenAmount: BigNumber;
}
export type EmergencyERC20RecoveredEvent = TypedEvent<
  [string, BigNumber],
  EmergencyERC20RecoveredEventObject
>;

export type EmergencyERC20RecoveredEventFilter =
  TypedEventFilter<EmergencyERC20RecoveredEvent>;

export interface EmergencyEtherRecoveredEventObject {
  amount: BigNumber;
}
export type EmergencyEtherRecoveredEvent = TypedEvent<
  [BigNumber],
  EmergencyEtherRecoveredEventObject
>;

export type EmergencyEtherRecoveredEventFilter =
  TypedEventFilter<EmergencyEtherRecoveredEvent>;

export interface KeysClearedEventObject {}
export type KeysClearedEvent = TypedEvent<[], KeysClearedEventObject>;

export type KeysClearedEventFilter = TypedEventFilter<KeysClearedEvent>;

export interface OwnerChangedEventObject {
  oldOwner: string;
  newOwner: string;
}
export type OwnerChangedEvent = TypedEvent<
  [string, string],
  OwnerChangedEventObject
>;

export type OwnerChangedEventFilter = TypedEventFilter<OwnerChangedEvent>;

export interface OwnerNominatedEventObject {
  newOwner: string;
}
export type OwnerNominatedEvent = TypedEvent<
  [string],
  OwnerNominatedEventObject
>;

export type OwnerNominatedEventFilter = TypedEventFilter<OwnerNominatedEvent>;

export interface SubmitPausedEventObject {
  new_status: boolean;
}
export type SubmitPausedEvent = TypedEvent<[boolean], SubmitPausedEventObject>;

export type SubmitPausedEventFilter = TypedEventFilter<SubmitPausedEvent>;

export interface TimelockChangedEventObject {
  timelock_address: string;
}
export type TimelockChangedEvent = TypedEvent<
  [string],
  TimelockChangedEventObject
>;

export type TimelockChangedEventFilter = TypedEventFilter<TimelockChangedEvent>;

export interface ValidatorAddedEventObject {
  pubKey: string;
  withdrawalCredential: string;
}
export type ValidatorAddedEvent = TypedEvent<
  [string, string],
  ValidatorAddedEventObject
>;

export type ValidatorAddedEventFilter = TypedEventFilter<ValidatorAddedEvent>;

export interface ValidatorArrayClearedEventObject {}
export type ValidatorArrayClearedEvent = TypedEvent<
  [],
  ValidatorArrayClearedEventObject
>;

export type ValidatorArrayClearedEventFilter =
  TypedEventFilter<ValidatorArrayClearedEvent>;

export interface ValidatorRemovedEventObject {
  pubKey: string;
  remove_idx: BigNumber;
  dont_care_about_ordering: boolean;
}
export type ValidatorRemovedEvent = TypedEvent<
  [string, BigNumber, boolean],
  ValidatorRemovedEventObject
>;

export type ValidatorRemovedEventFilter =
  TypedEventFilter<ValidatorRemovedEvent>;

export interface ValidatorsPoppedEventObject {
  times: BigNumber;
}
export type ValidatorsPoppedEvent = TypedEvent<
  [BigNumber],
  ValidatorsPoppedEventObject
>;

export type ValidatorsPoppedEventFilter =
  TypedEventFilter<ValidatorsPoppedEvent>;

export interface ValidatorsSwappedEventObject {
  from_pubKey: string;
  to_pubKey: string;
  from_idx: BigNumber;
  to_idx: BigNumber;
}
export type ValidatorsSwappedEvent = TypedEvent<
  [string, string, BigNumber, BigNumber],
  ValidatorsSwappedEventObject
>;

export type ValidatorsSwappedEventFilter =
  TypedEventFilter<ValidatorsSwappedEvent>;

export interface WithdrawalCredentialSetEventObject {
  _withdrawalCredential: string;
}
export type WithdrawalCredentialSetEvent = TypedEvent<
  [string],
  WithdrawalCredentialSetEventObject
>;

export type WithdrawalCredentialSetEventFilter =
  TypedEventFilter<WithdrawalCredentialSetEvent>;

export interface WithheldETHMovedEventObject {
  to: string;
  amount: BigNumber;
}
export type WithheldETHMovedEvent = TypedEvent<
  [string, BigNumber],
  WithheldETHMovedEventObject
>;

export type WithheldETHMovedEventFilter =
  TypedEventFilter<WithheldETHMovedEvent>;

export interface WithholdRatioSetEventObject {
  newRatio: BigNumber;
}
export type WithholdRatioSetEvent = TypedEvent<
  [BigNumber],
  WithholdRatioSetEventObject
>;

export type WithholdRatioSetEventFilter =
  TypedEventFilter<WithholdRatioSetEvent>;

export interface FrxETHMinter extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: FrxETHMinterInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    DEPOSIT_SIZE(overrides?: CallOverrides): Promise<[BigNumber]>;

    RATIO_PRECISION(overrides?: CallOverrides): Promise<[BigNumber]>;

    acceptOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    activeValidators(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    addValidator(
      validator: OperatorRegistry.ValidatorStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    addValidators(
      validatorArray: OperatorRegistry.ValidatorStruct[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    clearValidatorArray(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    currentWithheldETH(overrides?: CallOverrides): Promise<[BigNumber]>;

    depositContract(overrides?: CallOverrides): Promise<[string]>;

    depositEther(
      max_deposits: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    depositEtherPaused(overrides?: CallOverrides): Promise<[boolean]>;

    frxETHToken(overrides?: CallOverrides): Promise<[string]>;

    getValidator(
      i: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [string, string, string, string] & {
        pubKey: string;
        withdrawalCredentials: string;
        signature: string;
        depositDataRoot: string;
      }
    >;

    getValidatorStruct(
      pubKey: PromiseOrValue<BytesLike>,
      signature: PromiseOrValue<BytesLike>,
      depositDataRoot: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[OperatorRegistry.ValidatorStructOutput]>;

    moveWithheldETH(
      to: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    nominateNewOwner(
      _owner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    nominatedOwner(overrides?: CallOverrides): Promise<[string]>;

    numValidators(overrides?: CallOverrides): Promise<[BigNumber]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    popValidators(
      times: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    recoverERC20(
      tokenAddress: PromiseOrValue<string>,
      tokenAmount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    recoverEther(
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    removeValidator(
      remove_idx: PromiseOrValue<BigNumberish>,
      dont_care_about_ordering: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setTimelock(
      _timelock_address: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setWithdrawalCredential(
      _new_withdrawal_pubkey: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setWithholdRatio(
      newRatio: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    sfrxETHToken(overrides?: CallOverrides): Promise<[string]>;

    submit(
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    submitAndDeposit(
      recipient: PromiseOrValue<string>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    submitAndGive(
      recipient: PromiseOrValue<string>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    submitPaused(overrides?: CallOverrides): Promise<[boolean]>;

    swapValidator(
      from_idx: PromiseOrValue<BigNumberish>,
      to_idx: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    timelock_address(overrides?: CallOverrides): Promise<[string]>;

    togglePauseDepositEther(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    togglePauseSubmits(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    withholdRatio(overrides?: CallOverrides): Promise<[BigNumber]>;
  };

  DEPOSIT_SIZE(overrides?: CallOverrides): Promise<BigNumber>;

  RATIO_PRECISION(overrides?: CallOverrides): Promise<BigNumber>;

  acceptOwnership(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  activeValidators(
    arg0: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  addValidator(
    validator: OperatorRegistry.ValidatorStruct,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  addValidators(
    validatorArray: OperatorRegistry.ValidatorStruct[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  clearValidatorArray(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  currentWithheldETH(overrides?: CallOverrides): Promise<BigNumber>;

  depositContract(overrides?: CallOverrides): Promise<string>;

  depositEther(
    max_deposits: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  depositEtherPaused(overrides?: CallOverrides): Promise<boolean>;

  frxETHToken(overrides?: CallOverrides): Promise<string>;

  getValidator(
    i: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<
    [string, string, string, string] & {
      pubKey: string;
      withdrawalCredentials: string;
      signature: string;
      depositDataRoot: string;
    }
  >;

  getValidatorStruct(
    pubKey: PromiseOrValue<BytesLike>,
    signature: PromiseOrValue<BytesLike>,
    depositDataRoot: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<OperatorRegistry.ValidatorStructOutput>;

  moveWithheldETH(
    to: PromiseOrValue<string>,
    amount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  nominateNewOwner(
    _owner: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  nominatedOwner(overrides?: CallOverrides): Promise<string>;

  numValidators(overrides?: CallOverrides): Promise<BigNumber>;

  owner(overrides?: CallOverrides): Promise<string>;

  popValidators(
    times: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  recoverERC20(
    tokenAddress: PromiseOrValue<string>,
    tokenAmount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  recoverEther(
    amount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  removeValidator(
    remove_idx: PromiseOrValue<BigNumberish>,
    dont_care_about_ordering: PromiseOrValue<boolean>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setTimelock(
    _timelock_address: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setWithdrawalCredential(
    _new_withdrawal_pubkey: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setWithholdRatio(
    newRatio: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  sfrxETHToken(overrides?: CallOverrides): Promise<string>;

  submit(
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  submitAndDeposit(
    recipient: PromiseOrValue<string>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  submitAndGive(
    recipient: PromiseOrValue<string>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  submitPaused(overrides?: CallOverrides): Promise<boolean>;

  swapValidator(
    from_idx: PromiseOrValue<BigNumberish>,
    to_idx: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  timelock_address(overrides?: CallOverrides): Promise<string>;

  togglePauseDepositEther(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  togglePauseSubmits(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  withholdRatio(overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    DEPOSIT_SIZE(overrides?: CallOverrides): Promise<BigNumber>;

    RATIO_PRECISION(overrides?: CallOverrides): Promise<BigNumber>;

    acceptOwnership(overrides?: CallOverrides): Promise<void>;

    activeValidators(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    addValidator(
      validator: OperatorRegistry.ValidatorStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    addValidators(
      validatorArray: OperatorRegistry.ValidatorStruct[],
      overrides?: CallOverrides
    ): Promise<void>;

    clearValidatorArray(overrides?: CallOverrides): Promise<void>;

    currentWithheldETH(overrides?: CallOverrides): Promise<BigNumber>;

    depositContract(overrides?: CallOverrides): Promise<string>;

    depositEther(
      max_deposits: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    depositEtherPaused(overrides?: CallOverrides): Promise<boolean>;

    frxETHToken(overrides?: CallOverrides): Promise<string>;

    getValidator(
      i: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [string, string, string, string] & {
        pubKey: string;
        withdrawalCredentials: string;
        signature: string;
        depositDataRoot: string;
      }
    >;

    getValidatorStruct(
      pubKey: PromiseOrValue<BytesLike>,
      signature: PromiseOrValue<BytesLike>,
      depositDataRoot: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<OperatorRegistry.ValidatorStructOutput>;

    moveWithheldETH(
      to: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    nominateNewOwner(
      _owner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    nominatedOwner(overrides?: CallOverrides): Promise<string>;

    numValidators(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<string>;

    popValidators(
      times: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    recoverERC20(
      tokenAddress: PromiseOrValue<string>,
      tokenAmount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    recoverEther(
      amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    removeValidator(
      remove_idx: PromiseOrValue<BigNumberish>,
      dont_care_about_ordering: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<void>;

    setTimelock(
      _timelock_address: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    setWithdrawalCredential(
      _new_withdrawal_pubkey: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    setWithholdRatio(
      newRatio: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    sfrxETHToken(overrides?: CallOverrides): Promise<string>;

    submit(overrides?: CallOverrides): Promise<void>;

    submitAndDeposit(
      recipient: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    submitAndGive(
      recipient: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    submitPaused(overrides?: CallOverrides): Promise<boolean>;

    swapValidator(
      from_idx: PromiseOrValue<BigNumberish>,
      to_idx: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    timelock_address(overrides?: CallOverrides): Promise<string>;

    togglePauseDepositEther(overrides?: CallOverrides): Promise<void>;

    togglePauseSubmits(overrides?: CallOverrides): Promise<void>;

    withholdRatio(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {
    "DepositEtherPaused(bool)"(
      new_status?: null
    ): DepositEtherPausedEventFilter;
    DepositEtherPaused(new_status?: null): DepositEtherPausedEventFilter;

    "DepositSent(bytes,bytes)"(
      pubKey?: PromiseOrValue<BytesLike> | null,
      withdrawalCredential?: null
    ): DepositSentEventFilter;
    DepositSent(
      pubKey?: PromiseOrValue<BytesLike> | null,
      withdrawalCredential?: null
    ): DepositSentEventFilter;

    "ETHSubmitted(address,address,uint256,uint256)"(
      sender?: PromiseOrValue<string> | null,
      recipient?: PromiseOrValue<string> | null,
      sent_amount?: null,
      withheld_amt?: null
    ): ETHSubmittedEventFilter;
    ETHSubmitted(
      sender?: PromiseOrValue<string> | null,
      recipient?: PromiseOrValue<string> | null,
      sent_amount?: null,
      withheld_amt?: null
    ): ETHSubmittedEventFilter;

    "EmergencyERC20Recovered(address,uint256)"(
      tokenAddress?: null,
      tokenAmount?: null
    ): EmergencyERC20RecoveredEventFilter;
    EmergencyERC20Recovered(
      tokenAddress?: null,
      tokenAmount?: null
    ): EmergencyERC20RecoveredEventFilter;

    "EmergencyEtherRecovered(uint256)"(
      amount?: null
    ): EmergencyEtherRecoveredEventFilter;
    EmergencyEtherRecovered(amount?: null): EmergencyEtherRecoveredEventFilter;

    "KeysCleared()"(): KeysClearedEventFilter;
    KeysCleared(): KeysClearedEventFilter;

    "OwnerChanged(address,address)"(
      oldOwner?: null,
      newOwner?: null
    ): OwnerChangedEventFilter;
    OwnerChanged(oldOwner?: null, newOwner?: null): OwnerChangedEventFilter;

    "OwnerNominated(address)"(newOwner?: null): OwnerNominatedEventFilter;
    OwnerNominated(newOwner?: null): OwnerNominatedEventFilter;

    "SubmitPaused(bool)"(new_status?: null): SubmitPausedEventFilter;
    SubmitPaused(new_status?: null): SubmitPausedEventFilter;

    "TimelockChanged(address)"(
      timelock_address?: null
    ): TimelockChangedEventFilter;
    TimelockChanged(timelock_address?: null): TimelockChangedEventFilter;

    "ValidatorAdded(bytes,bytes)"(
      pubKey?: null,
      withdrawalCredential?: null
    ): ValidatorAddedEventFilter;
    ValidatorAdded(
      pubKey?: null,
      withdrawalCredential?: null
    ): ValidatorAddedEventFilter;

    "ValidatorArrayCleared()"(): ValidatorArrayClearedEventFilter;
    ValidatorArrayCleared(): ValidatorArrayClearedEventFilter;

    "ValidatorRemoved(bytes,uint256,bool)"(
      pubKey?: null,
      remove_idx?: null,
      dont_care_about_ordering?: null
    ): ValidatorRemovedEventFilter;
    ValidatorRemoved(
      pubKey?: null,
      remove_idx?: null,
      dont_care_about_ordering?: null
    ): ValidatorRemovedEventFilter;

    "ValidatorsPopped(uint256)"(times?: null): ValidatorsPoppedEventFilter;
    ValidatorsPopped(times?: null): ValidatorsPoppedEventFilter;

    "ValidatorsSwapped(bytes,bytes,uint256,uint256)"(
      from_pubKey?: null,
      to_pubKey?: null,
      from_idx?: null,
      to_idx?: null
    ): ValidatorsSwappedEventFilter;
    ValidatorsSwapped(
      from_pubKey?: null,
      to_pubKey?: null,
      from_idx?: null,
      to_idx?: null
    ): ValidatorsSwappedEventFilter;

    "WithdrawalCredentialSet(bytes)"(
      _withdrawalCredential?: null
    ): WithdrawalCredentialSetEventFilter;
    WithdrawalCredentialSet(
      _withdrawalCredential?: null
    ): WithdrawalCredentialSetEventFilter;

    "WithheldETHMoved(address,uint256)"(
      to?: PromiseOrValue<string> | null,
      amount?: null
    ): WithheldETHMovedEventFilter;
    WithheldETHMoved(
      to?: PromiseOrValue<string> | null,
      amount?: null
    ): WithheldETHMovedEventFilter;

    "WithholdRatioSet(uint256)"(newRatio?: null): WithholdRatioSetEventFilter;
    WithholdRatioSet(newRatio?: null): WithholdRatioSetEventFilter;
  };

  estimateGas: {
    DEPOSIT_SIZE(overrides?: CallOverrides): Promise<BigNumber>;

    RATIO_PRECISION(overrides?: CallOverrides): Promise<BigNumber>;

    acceptOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    activeValidators(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    addValidator(
      validator: OperatorRegistry.ValidatorStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    addValidators(
      validatorArray: OperatorRegistry.ValidatorStruct[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    clearValidatorArray(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    currentWithheldETH(overrides?: CallOverrides): Promise<BigNumber>;

    depositContract(overrides?: CallOverrides): Promise<BigNumber>;

    depositEther(
      max_deposits: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    depositEtherPaused(overrides?: CallOverrides): Promise<BigNumber>;

    frxETHToken(overrides?: CallOverrides): Promise<BigNumber>;

    getValidator(
      i: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getValidatorStruct(
      pubKey: PromiseOrValue<BytesLike>,
      signature: PromiseOrValue<BytesLike>,
      depositDataRoot: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    moveWithheldETH(
      to: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    nominateNewOwner(
      _owner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    nominatedOwner(overrides?: CallOverrides): Promise<BigNumber>;

    numValidators(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    popValidators(
      times: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    recoverERC20(
      tokenAddress: PromiseOrValue<string>,
      tokenAmount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    recoverEther(
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    removeValidator(
      remove_idx: PromiseOrValue<BigNumberish>,
      dont_care_about_ordering: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setTimelock(
      _timelock_address: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setWithdrawalCredential(
      _new_withdrawal_pubkey: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setWithholdRatio(
      newRatio: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    sfrxETHToken(overrides?: CallOverrides): Promise<BigNumber>;

    submit(
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    submitAndDeposit(
      recipient: PromiseOrValue<string>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    submitAndGive(
      recipient: PromiseOrValue<string>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    submitPaused(overrides?: CallOverrides): Promise<BigNumber>;

    swapValidator(
      from_idx: PromiseOrValue<BigNumberish>,
      to_idx: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    timelock_address(overrides?: CallOverrides): Promise<BigNumber>;

    togglePauseDepositEther(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    togglePauseSubmits(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    withholdRatio(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    DEPOSIT_SIZE(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    RATIO_PRECISION(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    acceptOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    activeValidators(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    addValidator(
      validator: OperatorRegistry.ValidatorStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    addValidators(
      validatorArray: OperatorRegistry.ValidatorStruct[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    clearValidatorArray(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    currentWithheldETH(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    depositContract(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    depositEther(
      max_deposits: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    depositEtherPaused(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    frxETHToken(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getValidator(
      i: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getValidatorStruct(
      pubKey: PromiseOrValue<BytesLike>,
      signature: PromiseOrValue<BytesLike>,
      depositDataRoot: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    moveWithheldETH(
      to: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    nominateNewOwner(
      _owner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    nominatedOwner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    numValidators(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    popValidators(
      times: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    recoverERC20(
      tokenAddress: PromiseOrValue<string>,
      tokenAmount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    recoverEther(
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    removeValidator(
      remove_idx: PromiseOrValue<BigNumberish>,
      dont_care_about_ordering: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setTimelock(
      _timelock_address: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setWithdrawalCredential(
      _new_withdrawal_pubkey: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setWithholdRatio(
      newRatio: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    sfrxETHToken(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    submit(
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    submitAndDeposit(
      recipient: PromiseOrValue<string>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    submitAndGive(
      recipient: PromiseOrValue<string>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    submitPaused(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    swapValidator(
      from_idx: PromiseOrValue<BigNumberish>,
      to_idx: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    timelock_address(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    togglePauseDepositEther(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    togglePauseSubmits(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    withholdRatio(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
