/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as depositContractSol from "./DepositContract.sol";
export type { depositContractSol };
import type * as erc20 from "./ERC20";
export type { erc20 };
import type * as utils from "./Utils";
export type { utils };
export type { IsfrxETH } from "./IsfrxETH";
export type { OperatorRegistry } from "./OperatorRegistry";
export type { FrxETH } from "./FrxETH";
export type { FrxETHMinter } from "./FrxETHMinter";
export type { SfrxETH } from "./SfrxETH";
